services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /goinfre/pg-data:/var/lib/postgresql/data
    env_file: ".env"

  django:
    build:
      context: ./
      dockerfile: ./django/dockerfile
    ports:
      - "8001:8001"
    volumes:
      - /goinfre/django-images:/djangodir/mysite/media
    env_file: ".env"
    depends_on:
      - db

  front:
    build: ./frontend/srcs
    ports:
      - "8000:443"
    depends_on:
      - django