services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /goinfre/bguillau/pg-data:/var/lib/postgresql/data
    env_file: ".env"


  django:
    build:
      context: ./
      dockerfile: ./django/dockerfile
    ports:
      - "8001:8001"
    env_file: ".env"
    depends_on:
      - db

  front:
    build: ./frontend/srcs
    ports:
      - "8000:80"
    depends_on:
      - django



