# Generated by Django 5.1.2 on 2024-10-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
                ('nb_player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_2fa', models.BooleanField(default=False)),
                ('birth_date', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('account_create', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('score_player1', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.tournament')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='base.user')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='base.user')),
            ],
        ),
    ]
