# Generated by Django 5.1.2 on 2024-10-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_game_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG_TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
