# Generated by Django 5.1.2 on 2024-10-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_friend_invite_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend_invite',
            name='unique_friend_invite',
        ),
    ]
