# Generated by Django 5.1.2 on 2024-10-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_friend_invite_unique_friend_invite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
