# Generated by Django 5.1.2 on 2024-10-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
    ]
