# Generated by Django 5.1.2 on 2024-10-21 09:58

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_friend_invite_friendrequest_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_test',
            name='img',
            field=models.ImageField(default='pad.webp', upload_to=base.utils.rename_image),
        ),
    ]
