# Generated by Django 5.1.2 on 2024-10-21 10:08

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_img_test_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='pad.webp', upload_to=base.utils.rename_image),
        ),
    ]
