# Utiliser l'image officielle Nginx
FROM nginx:latest

# Copier le fichier de configuration personnalisé pour Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# # Copier les fichiers statiques du frontend, si nécessaire
# COPY /path/to/your/static/files /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80
