# nginx/Dockerfile

FROM nginx:latest

# Copie le fichier de config
COPY nginx.conf /etc/nginx/nginx.conf

# # Copier les fichiers statiques du frontend, si nécessaire
# COPY /path/to/your/static/files /usr/share/nginx/html

EXPOSE 80
