FROM python:3.10-bullseye

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
# no pip update
ENV PYTHONDONTWRITEBYTECODE=1
# no .pyc
ENV PYTHONUNBUFFERED=1
# no buffer (if crash, all data is written to stdout/err)

RUN mkdir /djangodir

COPY ./. /djangodir/

RUN pip install -r /djangodir/requirements.txt

WORKDIR /djangodir/mysite/

EXPOSE 8001

ENTRYPOINT ["./launch.sh"]
