FROM nginx:latest


RUN rm /etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d/
COPY ./. /www/
RUN chmod 755 /etc/nginx/nginx.conf

RUN mkdir /etc/nginx/ssl/
COPY ./cert.pem /etc/nginx/ssl/
COPY ./key.pem /etc/nginx/ssl/

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]